modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
    modId="biomeapi"
    version="${file.jarVersion}"
    displayName="Biome Api"
    authors="LegibleSleet827"
    description='''
    This mod adds a datagen class which helps in biome creation
    '''

[[dependencies.biomeapi]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.biomeapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
